### ISSUE TITLE
500 Error

### ISSUE THREAD

**Issue by xadamxk** [pacexy/poro#7]
I know you updated the readme to say you'll be back next month, but I wanted to ask if you had a working example I could get from you when the library is functional? Or further documentation?

I have something pretty basic, but the console is returning:
```const { leaguepedia } = require('poro')


async function test() {
  const matchSchedule = await leaguepedia.fetchMatchSchedule({
    where: `_pageName LIKE "%2021%" AND Team1 = "TSM" OR MatchDay > 10`,
    groupBy: ['Team1', 'Team2'],
    orderBy: [{ field: 'DateTime_UTC', type: 'DESC' }, '_pageName'],
    limit: 100,
    offset: 50,
  })
  console.log(matchSchedule)
  return matchSchedule
}

test();
```

```(node:1184) UnhandledPromiseRejectionWarning: Error: Request failed with status code 500
    at createError (C:\Users\Adam\Documents\GitHub\lol-esports-test\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\Adam\Documents\GitHub\lol-esports-test\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (C:\Users\Adam\Documents\GitHub\lol-esports-test\node_modules\axios\lib\adapters\http.js:236:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1184) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which 
was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1184) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```


I apologize if I missed something but I read over the readme and something seems to be off for me

**Comment by pacexy** [comment]
Sorry for that.
This is because leaguepedia API has changed.
I am refactoring this repo, it will be published this week.
